//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewKaro
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Review()
        {
            this.AssignedReviewDetails = new HashSet<AssignedReviewDetail>();
            this.ReviewSubmissions = new HashSet<ReviewSubmission>();
        }
    
        public long Id { get; set; }

         
        public string Agenda { get; set; }
        public System.DateTime ReviewCycleStartDate { get; set; }
        public System.DateTime ReviewCycleEndDate { get; set; }
        public byte MinRate { get; set; }
        public byte MaxRate { get; set; }
        public string Description { get; set; }
        public int OrganizationId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedReviewDetail> AssignedReviewDetails { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewSubmission> ReviewSubmissions { get; set; }
    }
}
